### ISSUE TITLE
Seems like a validation step has been added since publication

### ISSUE THREAD

**Issue by kfprugger** [jboeshart/ReplicateBlobAzureFunction#1]
Hi Jason,

I have a customer that could REALLY use your code. I love the documentation, but it seems like there is something new happening in the validation when you setup the event grid subscription. When I copy out the Azure Function URL for the webhook and go over to the storage account and try to paste it into a webhook area of the subscription, I get a nice error saying that validation failed.

In reading some some of the MSFT docs, it seems that the validation should be occurring automatically, but it doesn't seem to be happening in this case. 

I found a stackoverflow article outlining something like this happening in Feb '18. Maybe that's what's going on with your code, too?

https://stackoverflow.com/questions/46580378/validation-not-strictly-required-for-event-grid-subscriptions

Attaching the screenshot of the error

JSON of the error:
<img width="1045" alt="errorwebhook1" src="https://user-images.githubusercontent.com/20729981/50992408-15f5b000-14e5-11e9-86cc-050ce6d608d9.PNG">

    "submissionTimestamp": "2019-01-10T19:27:32.0690111Z",
    "subscriptionId": "xxxx-xxxx-xxxxxx-cd6d26fbbd59",
    "properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"Url validation\",\"message\":\"The attempt to validate the provided endpoint https://robrakfxsync.azurewebsites.net/api/src-blob-http-trigger failed. For more details, visit https://aka.ms/esvalidation.\"}]}}"
    },

**Comment by kfprugger** [comment]
Update: I tried using the authentication of "anonymous" with another http triggered function I created. Still getting the same response. 

Here's the output from the Logs console.

2019-01-10T19:55:49  Welcome, you are now connected to log-streaming service.
2019-01-10T19:56:00.445 [Information] Executing 'Functions.anontrig1' (Reason='This function was programmatically called via the host APIs.', Id=47d3870a-d301-4dc9-94d8-db08fb0ec262)
2019-01-10T19:56:00.656 [Error] Function compilation error
Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2019-01-10T19:56:00.734 [Warning] run.csx(12,62): warning CS0618: 'TraceWriter' is obsolete: 'Will be removed in an upcoming version. Use Microsoft.Extensions.Logging.ILogger instead.'
2019-01-10T19:56:00.801 [Error] run.csx(103,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:01.046 [Error] run.csx(111,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:01.122 [Error] run.csx(131,20): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:01.198 [Error] run.csx(137,16): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:01.301 [Error] Executed 'Functions.anontrig1' (Failed, Id=47d3870a-d301-4dc9-94d8-db08fb0ec262)
Script compilation failed.
2019-01-10T19:56:21.198 [Information] Executing 'Functions.anontrig1' (Reason='This function was programmatically called via the host APIs.', Id=4233710d-d4df-49ae-acea-1a63434c1adf)
2019-01-10T19:56:21.235 [Error] Function compilation error
Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2019-01-10T19:56:21.293 [Warning] run.csx(12,62): warning CS0618: 'TraceWriter' is obsolete: 'Will be removed in an upcoming version. Use Microsoft.Extensions.Logging.ILogger instead.'
2019-01-10T19:56:21.342 [Error] run.csx(103,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:21.419 [Error] run.csx(111,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:21.498 [Error] run.csx(131,20): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:21.574 [Error] run.csx(137,16): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:21.771 [Error] Executed 'Functions.anontrig1' (Failed, Id=4233710d-d4df-49ae-acea-1a63434c1adf)
Script compilation failed.
2019-01-10T19:56:21.928 [Information] Executing 'Functions.anontrig1' (Reason='This function was programmatically called via the host APIs.', Id=816638e5-54f6-49cf-a9de-73c67f16d3e8)
2019-01-10T19:56:21.963 [Error] Function compilation error
Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2019-01-10T19:56:22.020 [Warning] run.csx(12,62): warning CS0618: 'TraceWriter' is obsolete: 'Will be removed in an upcoming version. Use Microsoft.Extensions.Logging.ILogger instead.'
2019-01-10T19:56:22.046 [Error] run.csx(103,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:22.133 [Error] run.csx(111,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:22.210 [Error] run.csx(131,20): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:22.365 [Error] run.csx(137,16): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:22.441 [Error] Executed 'Functions.anontrig1' (Failed, Id=816638e5-54f6-49cf-a9de-73c67f16d3e8)
Script compilation failed.
2019-01-10T19:56:22.523 [Information] Executing 'Functions.anontrig1' (Reason='This function was programmatically called via the host APIs.', Id=167c5a8d-af98-4b1b-bc1d-0da1b2a1e6b8)
2019-01-10T19:56:22.570 [Error] Function compilation error
Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2019-01-10T19:56:22.624 [Warning] run.csx(12,62): warning CS0618: 'TraceWriter' is obsolete: 'Will be removed in an upcoming version. Use Microsoft.Extensions.Logging.ILogger instead.'
2019-01-10T19:56:22.651 [Error] run.csx(103,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:22.723 [Error] run.csx(111,24): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:22.798 [Error] run.csx(131,20): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:23.013 [Error] run.csx(137,16): error CS1501: No overload for method 'CreateResponse' takes 2 arguments
2019-01-10T19:56:23.111 [Error] Executed 'Functions.anontrig1' (Failed, Id=167c5a8d-af98-4b1b-bc1d-0da1b2a1e6b8)
Script compilation failed.
